In [5]:
l=[1, 2344,545,6,7]

In [6]:
l

[1, 2344, 545, 6, 7]

In [7]:
import numpy as np

In [8]:
a= np.array(l)

In [9]:
a

array([   1, 2344,  545,    6,    7])

In [10]:
b=np.array([12,55,63.3,True,"abc"])

In [11]:
b

array(['12', '55', '63.3', 'True', 'abc'], dtype='|S32')

In [12]:
type(b)

numpy.ndarray

In [13]:
l.pop

<function pop>

In [14]:
l.pop()

7

In [15]:
l

[1, 2344, 545, 6]

In [16]:
b.mean()

TypeError: cannot perform reduce with flexible type

In [17]:
a.mean()

580.6

In [18]:
a

array([   1, 2344,  545,    6,    7])

In [19]:
l

[1, 2344, 545, 6]

In [20]:
l

[1, 2344, 545, 6]

In [21]:
l[1:]

[2344, 545, 6]

In [22]:
l[0:2]

[1, 2344]

In [23]:
l[: : 2]

[1, 545]

In [24]:
a

array([   1, 2344,  545,    6,    7])

In [25]:
a[2:]

array([545,   6,   7])

In [26]:
a[2:4]

array([545,   6])

In [27]:
l

[1, 2344, 545, 6]

In [28]:
b=a[2:4]

In [29]:
b

array([545,   6])

In [32]:
b[:]=111

In [33]:
b

array([111, 111])

In [34]:
a

array([   1, 2344,  111,  111,    7])

In [37]:
c=a.copy()

In [38]:
c

array([   1, 2344,  111,  111,    7])

In [39]:
c[0]

1

In [40]:
c[0]=2345

In [41]:
c

array([2345, 2344,  111,  111,    7])

In [42]:
a

array([   1, 2344,  111,  111,    7])